INCLUDE := -I ~/include
LDFLAGS := -L ~/lib -lsense -lm

all: clockDisplay


clockDisplay: main.o display.o
	cc -o clockDisplay main.o display.o $(LDFLAGS)


main.o: main.c display.h
	cc -c main.c -I ~/include
display.o: display.c display.h
	cc -c display.c -I ~/include

run:  
	./clock.sh | ./clockDisplay

clean:
	rm -f *.o clockDisplay
